name: 🚀 Build and Push Docker Image

on:
  push:
    branches: [ main ]  # runs on code push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v3

    - name: 🐳 Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 🛠️ Build Docker image
      run: docker build -t sujalgp/forest-fire-app .

    - name: 🚀 Push image to Docker Hub
      run: docker push sujalgp/forest-fire-app